log4j.rootLogger=ERROR, CONSOLE, ecommerce

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d [%t] %-5p %c - %m%n

log4j.appender.ecommerce=org.apache.log4j.DailyRollingFileAppender
log4j.appender.ecommerce.File=${ecommerce.home}/logs/ecommerce.log
log4j.appender.ecommerce.DatePattern='.'yyyy-MM-dd
log4j.appender.ecommerce.layout=org.apache.log4j.PatternLayout
log4j.appender.ecommerce.layout.ConversionPattern=%d [%t] %-5p %c - %m%n

log4j.logger.com.atcloud=DEBUG
log4j.logger.mx.intran.ecommerce=DEBUG